global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:9201']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s

  - job_name: 'note-service'
    static_configs:
      - targets: ['note-service:9202']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s

  - job_name: 'search-service'
    static_configs:
      - targets: ['search-service:9203']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s

  - job_name: 'gateway-service'
    static_configs:
      - targets: ['gateway-service:9200']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
