apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: scrib-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
      - name: gateway-service
        image: scrib/gateway-service:latest
        ports:
        - containerPort: 9200
        env:
        - name: SPRING_REDIS_HOST
          value: redis-service
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 9200
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 9200
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: scrib-backend
  type: LoadBalancer
spec:
  selector:
    app: gateway-service
  ports:
  - port: 80
    targetPort: 9200
