apiVersion: apps/v1
kind: Deployment
metadata:
  name: note-service
  namespace: scrib-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: note-service
  template:
    metadata:
      labels:
        app: note-service
    spec:
      containers:
      - name: note-service
        image: scrib/note-service:latest
        ports:
        - containerPort: 9202
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://ec2-65-1-185-194.ap-south-1.compute.amazonaws.com:5432/scrib
        - name: SPRING_DATASOURCE_USERNAME
          value: summitcodeworks
        - name: SPRING_DATASOURCE_PASSWORD
          value: 8ivhaah8
        - name: SPRING_REDIS_HOST
          value: redis-service
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 9202
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 9202
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: note-service
  namespace: scrib-backend
spec:
  selector:
    app: note-service
  ports:
  - port: 9202
    targetPort: 9202
