apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: scrib-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: scrib/user-service:latest
        ports:
        - containerPort: 9201
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://ec2-65-1-185-194.ap-south-1.compute.amazonaws.com:5432/scrib
        - name: SPRING_DATASOURCE_USERNAME
          value: summitcodeworks
        - name: SPRING_DATASOURCE_PASSWORD
          value: 8ivhaah8
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 9201
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 9201
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: scrib-backend
spec:
  selector:
    app: user-service
  ports:
  - port: 9201
    targetPort: 9201
