server:
  port: 9200

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:9201
          predicates:
            - Path=/api/users/**
        - id: note-service
          uri: http://localhost:9202
          predicates:
            - Path=/api/notes/**
        - id: note-websocket
          uri: http://localhost:9202
          predicates:
            - Path=/ws/**
        - id: search-service
          uri: http://localhost:9203
          predicates:
            - Path=/api/search/**
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 10
            redis-rate-limiter.burstCapacity: 20
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

logging:
  level:
    com.scrib.gatewayservice: DEBUG
    org.springframework.cloud.gateway: DEBUG
